spring:
  config:
    import: aws-secretsmanager:sqs-creds
  application:
    name: sqs-poc
  cloud:
    aws:
      credentials:
        access-key: ${access_key}
        secret-key: ${secret_key}
      region:
        static: us-east-1
  datasource:
    #url: jdbc-secretsmanager:postgresql://rds-test-db.czmuci46ietm.us-east-1.rds.amazonaws.com:5432/postgres
    url: jdbc:postgresql://rds-test-db.czmuci46ietm.us-east-1.rds.amazonaws.com:5432/postgres
    #username: rds!db-95505ded-d1cc-43f6-acd0-efc7c7c5fa85
    username: postgres
    #driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    driver-class-name: org.postgresql.Driver
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
sqs:
  queue:
    url: ${ecomm_queue_url}